### ISSUE TITLE
Article on ContentType Guidance

### ISSUE THREAD

**Issue by PascalStrassl** [OfficeDev/PnP-Guidance#108]
As far as i know: Best Practice is to create ContentTypes only on the Rootweb of the Site Collection. 
Just wanted to share some resources on that with a colleague, but couldn't find this in the pnp-articles.

I would have expected the information in this article:
https://msdn.microsoft.com/en-us/pnp_articles/site-columns-and-content-types-sharepoint-add-in

The only place where i can find this is in the following comment of the "ObjectContentType.cs":

> // if this is a sub site then we're not provisioning content types. Technically this can be done but it's not a recommended practice
https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

So it would be nice to get more detail about the reason why this is not recommended.

**Comment by jansenbe** [comment]
Hi @PascalStrassl , it would indeed be good to further explain this best practice in one of the articles.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
