### ISSUE TITLE
searched based nav

### ISSUE THREAD

**Issue by russgove** [OfficeDev/PnP-Guidance#133]
hi, 
excellent series of articles. thanks,
the discussion on navigation seemed to write off search based nave, and did not even mention security trimming.

is there a reason  search based nav is discouraged?
can security trimming be added to the other options?

**Comment by jansenbe** [comment]
Hi Russel,

We did not intentionally drop search based navigation, it's just that it's not widely used. We'll adjust to guidance to also mention this. When it comes to security trimming: search and structural navigation are security trimmed, managed navigation is not ==> I'll update the article to clarify that.

Thanks for the great feedback!

**Comment by jansenbe** [comment]
Article has been updated. Closing this issue now
