### ISSUE TITLE
Rendering JSON from an XSLTListViewWebPart

### ISSUE THREAD

**Issue by russgove** [OfficeDev/PnP-Guidance#134]
Hi, The article on performance gave great advice on optimizing ajax calls. I've found one of the best optimizations was to avoid making the ajax call at all and just delivering the content on the initial payload from a listviewwebpart.. 

https://yetanothersharepointblog.wordpress.com/2014/04/09/rendering-json-from-an-xsltlistviewwebpart/

It would be great if this was supported out-of the box.

It would be even better if an SPFX webpart could include a CAML(or rest)  query in its manifest that specified the data it needed to start, and that data was just there automatically when the webpart started without making any ajax calls.

**Comment by jansenbe** [comment]
Hi Russel,

That's indeed a good idea when CAML based queries caching does work server side...and it does, but since we've so many WFE's per farm the cache hit ratio will be very low and hence there's not so many benefits from doing this.
