### ISSUE TITLE
Unable to fully Provision UnifiedGroup using New-PnPUnifiedGroup

### ISSUE THREAD

**Issue by lleVall** [OfficeDev/PnP-Guidance#140]
Hello, 

I'm trying to provision programmatically an Unified group using the following command:

_New-PnPUnifiedGroup -DisplayName "PnpGroup1" -Description "Group Created With Pnp" -MailNickname "PnpGroup1" -Members "xxx@xxx.onmicrosoft.com" -IsPrivate_

The group itself is well provision but the linked sharepoint site collection is never provision. After two days, the "Site Url" property of my unifiedgroup still returns "Unable to provision resource".

![image](https://user-images.githubusercontent.com/29457637/27184948-091e3444-51e4-11e7-9760-42c5cd373879.png)

Note that if I browse through the group using outlook online and then I click on the "file" tab and the button "browse library" then it triggers the sharepoint site collection creation.

Is there a way to fully generate the unified group (and the linked sharepoint site collection) using cmdlet ?

Thx for your feedback

**Comment by benstegink** [comment]
I'm having the same issues, every once in a while when provisioning a new group, the SiteUrl is stuck with "Resource provisioning is in progress".  Then, after some time it just failed.  I've also seen people commenting here - https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8215 that are experiencing the same issue of inconsistent/random failures to provision sites.

**Comment by crossan007** [comment]
Yep - I'm seeing this too.

Interestingly, If I create a new "Microsoft Team,"  the Unified group is created, and the SharePoint site gets stuck.

Maybe it's the integration between Unified Groups and SharePoint online?

**Comment by VesaJuvonen** [comment]
Closing for now as we are removing this repository from GitHub to avoid confusion. If this is still a valid issue or a question, we would recommend opening an issue at http://aka.ms/spdev-issues. Sorry for the inconvenience.
