### ISSUE TITLE
The links like "Provisioning.Pages sample" redirect to 404 pageck the redirected page (VSTS BUG 1480337)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#155]
Repro Steps:
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/modify-sharepoint-site-permissions-and-get-external-sharing-status
2.Click the link and check the redirected page

![downloadattachment 2](https://user-images.githubusercontent.com/16706698/30744664-6ba47f58-9fa3-11e7-8578-10084bc4f7fb.png)

Actual Result:
  The links like "Provisioning.Pages sample" redirect to 404 page
Expected Result:
  The links like "Provisioning.Pages sample" redirect to  correct page

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
