### ISSUE TITLE
Incorrect formatting of bullets in IE11 (VSTS BUG 1480313)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#156]
![attachfilehandler](https://user-images.githubusercontent.com/16706698/30744888-59c6961c-9fa4-11e7-975b-7ef4bc3a851a.png)

Repro Steps:
1. Navigate to https://msdn.microsoft.com/zh-cn/pnp_articles/Sandbox-Solution-Transformation-Guidance-Feature-Receivers
For US topic open this page in IE11: https://msdn.microsoft.com/en-us/pnp_articles/Sandbox-Solution-Transformation-Guidance-Feature-Receivers#options-for-replacing-feature-receivers 
2.Check the bullet in page

Actual Result:
 The format of bullet dispalys incorrectly
 
Expected Result:
 The format of bullet dispalys correctly

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
