### ISSUE TITLE
Link "me" does not redirect to twitter account (VSTS BUG 1477168)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#164]
Repro Steps:
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/Introducing-the-PnP-Provisioning-Engine
2.Find "Introducing the PnP Provisioning Engine" section
![attachfilehandler 6](https://user-images.githubusercontent.com/16706698/30746818-65fc08b6-9fab-11e7-8165-b86633868bef.png)

Actual Result:
This link is jump error.
 
Expected Result:
This link should jump correct.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
