### ISSUE TITLE
The link  "Provisioning templates" redirect to page that does not exist (VSTS BUG 1480356)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#167]
Repro Steps:
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/pnp-provisioning-framework#1-model-your-site-and-the-site-artifacts
2.Click the link and check the redirected page
 
![attachfilehandler 8](https://user-images.githubusercontent.com/16706698/30747408-792a0c56-9fad-11e7-9642-c24ac87edba7.png)

Actual Result:
The link  "sample project" redirect to 404 page
Expected Result:
The link  "sample project" redirect to correct pae

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
