### ISSUE TITLE
The link "Core.OfficeWebWidgets" redirect to 404 page (VSTS BUG 1477128)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#175]
Repro Steps
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/display-information-from-a-host-site-by-using-office-web-widgets
2.Click the link and check the link redirected page
 
![attachfilehandler 14](https://user-images.githubusercontent.com/16706698/30748852-d7ee0ce8-9fb1-11e7-8d4e-370a7bdf7fcf.png)

Actual Result:
 The link redirect to 404 page

Expected Result:
 The link redirect to correct page

**Comment by ghost** [comment]
@VesaJuvonen  Do you know if this sample code still exists? We're pointing to it from this doc: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/display-information-from-a-host-site-by-using-office-web-widgets

**Comment by VesaJuvonen** [comment]
The article has been removed from the TOC and site to avoid confusion. This was based on experimental components from Office Extensibility team which were never actually released for production usage.
