### ISSUE TITLE
The link "ECM.Autotagging sample app" redirects to 404 page (VSTS BUG 1477176)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#177]
Repro Steps:
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/Document-library-templates-sample-app-for-SharePoint
2.Click the link and check the Broken link:
"ECM.Autotagging sample app"

Actual Result:
 The link redirect to 404 page.
 
Expected Result:
 The link redirect to correct page.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
