### ISSUE TITLE
Incorrect formatting - sentence split into two parts (VSTS BUG 1477231)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#181]
Repro Steps:
1. navigate to https://msdn.microsoft.com/en-us/pnp_articles/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites#option-1-upload-a-zip-file-with-the-webjob-binaries-to-your-azure-portal  
![attachfilehandler 17](https://user-images.githubusercontent.com/16706698/30750057-aba9a30a-9fb5-11e7-960a-ec6e55776df9.png)

Actual result:
Sentence is not placed under the picture

Expected result
Sentence should be placed under the picture

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
