### ISSUE TITLE
Incorrect formatting - Text is next to the picture instead of above it (VSTS BUG 1477254)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#182]
Repro Steps:
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites

![downloadattachment 7](https://user-images.githubusercontent.com/16706698/30750287-55a7cd6e-9fb6-11e7-853e-33a813d690e8.png)

Actual Result:
 Some text displays incorrect on page 
Expected Result:
Some text displays correct on page

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
