### ISSUE TITLE
Dev Center: Some strings are truncated in device toolbar mode (VSTS BUG 1493561)

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/PnP-Guidance#185]
Repro Steps
1. Navigate to https://msdn.microsoft.com/en-us/pnp_articles/Migrate-user-profile-properties-sample-app-for-SharePoint
2. Toggle device tool bar in chrome: F12 > hit the "Toggle device toolbar" button next to the select element button.
3. Proceed to change the device model based on the information below.
 
![repro](https://user-images.githubusercontent.com/16706698/30866370-5110a76e-a2d9-11e7-85f7-7ba544c8b2a7.png)

 
Actual Result:
 Some strings is truncated.
 
Expected Result:
Strings should not be truncated

Repro urls for Nexus5 device:
https://msdn.microsoft.com/en-us/pnp_articles/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth
https://msdn.microsoft.com/en-us/pnp_articles/Configure-SP-Provider-Hosted-Apps-For-Distribution
https://msdn.microsoft.com/en-us/pnp_articles/development-experience-tenant-apponly-permissions-in-sharepoint-online
https://msdn.microsoft.com/en-us/pnp_articles/Introducing-the-PnP-Provisioning-Engine
https://msdn.microsoft.com/en-us/pnp_articles/javascript-patterns-and-performance
https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-lists-and-libraries

Repro urls for iPhone6 device:
https://msdn.microsoft.com/en-us/pnp_articles/query-sharepoint-change-log-with-changequery-and-changeToken
https://msdn.microsoft.com/en-us/pnp_articles/Sandbox-Solution-Transformation-Guidance-InfoPath
https://msdn.microsoft.com/en-us/pnp_articles/search-customizations-for-sharepoint
https://msdn.microsoft.com/en-us/pnp_articles/timerjob-framework
https://msdn.microsoft.com/en-us/pnp_articles/Upload-user-profile-pictures-sample-app-for-SharePoint
https://msdn.microsoft.com/en-us/pnp_articles/upload-web-parts-in-sharepoint
https://msdn.microsoft.com/en-us/pnp_articles/use-asynchronous-operations-in-sharepoint-add-ins
https://msdn.microsoft.com/en-us/pnp_articles/Use-remote-event-receivers-in-SharePoint

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
