### ISSUE TITLE
Property bag guidance and supported approaches

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Guidance#19]
Article to collect all property bag keys and how they can be used to control settings, which are not available directly with CSOM. Things like.
- Publishing features - Available page layouts, web templates, default page layout
- Control Metadata driven navigation settings
- Enable records management in list level

One article with all the supported properties (table listed with sub chapters for additional details), including sample for each of them

**Comment by braegelno5** [comment]
The question for me is: on a future update of an existing property key with a new value exists there anywhere something written down what I must read before I should implement this for web and list?

**Comment by erwinvanhunen** [comment]
Just to be clear: In this case Vesa is not asking for code or an actual implementation. We're looking for a list of all properties in use out there and we want to document it's use.

We're almost done implementing the code to update existing propertybag values (however, the schema is not supporting it yet, that is still ongoing) and that we will merge likely somewhere today.

**Comment by braegelno5** [comment]
OK now this is cleared for me, but the list of all standard properties should come from corp insiders, or not?
If I put my custom project specific properties to this list this makes no sense, or?

**Comment by erwinvanhunen** [comment]
No, your custom project specific properties indeed have no place in this list. This is indeed more likely to originate from internal Microsoft, but people might be aware of the use of specific (system) properties and it's use that they can contribute.

**Comment by VesaJuvonen** [comment]
We did do a web cast around this and since we can't really get official list even from internal sources, I'll close this one for now.
