### ISSUE TITLE
Clarify conflicting guidance around how long to back off when being throttled

### ISSUE THREAD

**Issue by ahofman** [OfficeDev/PnP-Guidance#193]
There are a few official sources that provide advice on how to handle throttling (i.e., HTTP 429 responses) from SharePoint Online:

[Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#github-csom-code-samples-sharepoint-online-throttling) shows some code snippets that suggest using an **exponential backoff** with a base delay of **30 seconds**.

This is in contrast to [Updated Guidance around SharePoint Web Service Identification and Throttling](https://dev.office.com/blogs/updated-guidance-around-sharepoint-web-service-identification-and-throttling) which suggests "the correct behavior is to respect the 429 response and retry the request based on the retry-value in the 429 message." To date, we've seen that the Retry-After value in the 429 responses coming from SharePoint is always **120**. 

The key questions are

1. Should we use the Retry-After value or a hard-coded value? I'm guessing the Retry-After value would be preferable, as it allows SPO to alter the backoff period appropriately as the throttling limits change. 
2. If we use Retry-After, should we still use an exponential backoff for continued failures, or just always use whatever value was supplied in the Retry-After header?

As an aside, The [SharePoint Online Throttling Core Sample](https://github.com/SharePoint/PnP/tree/dev/Samples/Core.Throttling#handling-the-throttling-in-the-code) suggests the same as above, but has an inconsistent comment - the code says 30 seconds, but the comment says 10 seconds. I presume this is a typo and it's meant to be 30. 

Thanks :)

cc @VesaJuvonen

**Comment by ahofman** [comment]
Ping - any update here? @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Closing for now as we are removing this repository from GitHub to avoid confusion. If this is still a valid issue or a question, we would recommend opening an issue at http://aka.ms/spdev-issues. Sorry for the inconvenience.
