### ISSUE TITLE
Search for items in a specific Search Resource

### ISSUE THREAD

**Issue by ashkan89** [OfficeDev/PnP-Guidance#194]
Hello guys.
I want to search for items choosing a specific search resource.How can I determine the search resource while querying?
I and developing a SearchResult SPFx webpart and I need to have a property for Administrator to select one or more search resources in whitch the result items should be return.
And please help me how to determine the search resources to be filled in a multiselect dropdown.
Thnx

**Comment by VesaJuvonen** [comment]
Closing for now as we are removing this repository from GitHub to avoid confusion. If this is still a valid issue or a question, we would recommend opening an issue at http://aka.ms/spdev-issues.
