### ISSUE TITLE
Get-PnPStoredCredential example is using a different command

### ISSUE THREAD

**Issue by spg-iwilson** [OfficeDev/PnP-Guidance#195]
The help page for Get-PnPStoredCredential uses the command Get-SPOnlineStoredCredential

https://github.com/SharePoint/PnP-Guidance/blob/master/powershell/GetPnPStoredCredential.md

**Comment by VesaJuvonen** [comment]
Please have a look from the updated official docs at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpstoredcredential?view=sharepoint-ps.
