### ISSUE TITLE
Documentation for Description property seems to be incorrect

### ISSUE THREAD

**Issue by ghost** [OfficeDev/PnP-Guidance#197]
In the documentation for TeamSiteCollectionCreationInformation it states that the "Description" property is:
**_> The Guid of the site design to be used. If specified will override the SiteDesign property_**

However, I believe this property is used only to set the site's description, correct?  So this documentation appears to be incorrect here.  

That being said, I really am looking for a way to set the SiteDesign for new team sites to use a custom SiteDesign that is already deployed to my tenant.  So I was actually hoping that TeamSiteCollectionCreationInformation would allow me to specify a SiteDesign (by name or ID) as we can for Communication sites.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/sp-dev-docs#2008
