### ISSUE TITLE
Add-PnPClientSideWebPart not working for some of my webparts (component cannot be null)...

### ISSUE THREAD

**Issue by jca38** [OfficeDev/PnP-Guidance#198]
Hi,

Add-PnPClientSideWebPart is not working for some webparts (error : component cannot be null), and is working for others.
I use 
Add-PnPClientSideWebPart -Page "mypage" -Component "mywebpart" -Section 1 - Column 1

Not that I can add my webpart using the browser when editing the page, but I have the error only when trying to add it through Pnp powershell Cmdlet Add-PnpClientSideWebPart.

Thanks for your help!
Best Regards,
Jean-Christophe AUDARD

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-PowerShell#1609
