### ISSUE TITLE
-Checkout switch has issue with Add-PNPFile, not overriding field value(s)

### ISSUE THREAD

**Issue by HarshadBhoi** [OfficeDev/PnP-Guidance#199]
I am trying to execute below commands.

Add-PNPFile -Path "C:\Users\abc\Downloads\siteColumns.csv" -folder "Shared%20Documents" -Values @{Modified=(Get-Date).AddDays(-10);Editor='abc@xyz.com'} -CheckInComment "TestCheck In Comments by abc" -Checkout

It perfectly updates check in comment, but ignores -Values @{Modified=(Get-Date).AddDays(-10);Editor='abc@xyz.com'} and takes current date and current logged-in user.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-PowerShell#1608
