### ISSUE TITLE
App Model -> Add-in Model

### ISSUE THREAD

**Issue by SPDoctor** [OfficeDev/PnP-Guidance#34]
A lot of guidance material, PowerPoints etc. are referring to "App model". Would it be worth going through these now and updating with new nomenclature?

**Comment by VesaJuvonen** [comment]
thx Bill on this and sorry for the delay,
these have been waiting for some cleaning and got them now removed to avoid confusion with updated notes on the readme to updated locations around same content - https://github.com/OfficeDev/PnP-Guidance/tree/master/documentation
