### ISSUE TITLE
SharePoint 2013 site provisioning - link not working

### ISSUE THREAD

**Issue by KoenVosters** [OfficeDev/PnP-Guidance#37]

**Comment by KoenVosters** [comment]
GitHub not as smart as assumed, this is not a code issue, rather a documentation issue.

**Comment by VesaJuvonen** [comment]
Hi Koen,
This is unfortunately pretty old one, but do you remember which document this is referring to? I did scan some of the provisioning topics and double checked links. I've updated some of the articles, but since this is missing the actual one, can't confirm that it has been fixed.

**Comment by VesaJuvonen** [comment]
Closing, since could not find the issue from articles.
