### ISSUE TITLE
SharePoint site branding and page customization - Broken links

### ISSUE THREAD

**Issue by biste5** [OfficeDev/PnP-Guidance#39]
Hi,

the guidance in subject
[SharePoint site branding and page customization solutions](https://github.com/OfficeDev/PnP-Guidance/blob/master/articles/SharePoint-site-branding-and-page-customization-solutions.md)

contains many broken links. They are especially at the bottom section of the guidance.

**Comment by VesaJuvonen** [comment]
Thx Massimo, 
We'll get those also fixed. Notice that this is one of those articles which we have corresponding MSDN page, which has all links working. You can find it from following location: https://msdn.microsoft.com/en-us/library/office/dn985871.aspx

Regardless of this, we'll need to also keep the GitHub up to date or ensure that links are working properly. Will update them accordingly.

**Comment by biste5** [comment]
Hi Vesa,
you're right, MSDN articles seems to have all links working. I couldn't locate it myself, and trying to fix links in the article looked tedious or impossible to me.

I think I can help out to fix at least this article.

Cheers
Massimo

**Comment by biste5** [comment]
associated with PR 40 :)
