### ISSUE TITLE
FinishUpload does not honour Libraries ForceCheckout setting when set to false

### ISSUE THREAD

**Issue by stinkyfriend** [OfficeDev/PnP-Guidance#98]
On this page --> https://msdn.microsoft.com/en-us/pnp_articles/upload-large-files-sample-app-for-sharepoint is a method - UploadFileSlicePerSlice - I have re-purposed but essentially follows the same process i.e. if file is < 3MB use ContentStream otherwise upload the file in slices (StartUpload/ContinueUpload/FinishUpload).

I have discovered that the returned 'uploadFile' is in a different state depending on which of the two options are used. When attempting to access 'uploadFile' (e.g. ListItemAllFields) after FinishUpload an error is thrown saying can't access stream once closed. I added a ctx.Load(uploadFile) between the FinishUpload and the ctx.ExecuteQuery() and now uploadFile is returned from both paths in a similar state. Should the sample function be amended to show this?

However, further to this, it seems the slicing option does not honour the Libraries ForceCheckout and EnableVersioning settings when set to false.

After uploading a large file to a Library where "Document Version History" is set to "No Versioning" and the "Require Check Out" is set to "No". There are two versions of the file (one version for file upload and the other version where values on the ListItem are set) and the file is in a Checked Out state to the user who ran the upload.

I suspect only part of this issue is relevant to this repo.

**Comment by VesaJuvonen** [comment]
thx stinkyfriend on sharing this. We'll have a look on the sample and can perform suggested changes. We can't really fix the underlying CSOM API behavior through PnP process though. Let's anyway get the behavior properly documented in the sample with the suggested changes.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
